import { expectedDefinition, expectedField, expectedSection } from "./baseline-fidelity-helpers";

const half = { base: "full", md: 6 } as const;
const described = (description: string) => ({ description });
const describedHalf = (description: string) => ({ description, span: half });

export const profileDefinition = expectedDefinition("user-profile", "root", [
	expectedSection("root", 0, "personal", "Personal Information"),
	expectedField("personal", 0, "f-firstName", "firstName", "text", "First Name", { span: half }),
	expectedField("personal", 1, "f-lastName", "lastName", "text", "Last Name", { span: half }),
	expectedField("personal", 2, "f-email", "email", "email", "Email", { span: half }),
	expectedField("personal", 3, "f-age", "age", "number", "Age", { span: half }),
	expectedSection("root", 1, "work", "Work Details"),
	expectedField("work", 0, "f-role", "role", "select", "Role", { span: half }),
	expectedField("work", 1, "f-department", "department", "select", "Department", { span: half }),
	expectedSection("root", 2, "preferences", "Preferences"),
	expectedField("preferences", 0, "f-bio", "bio", "textarea", "Bio", described("Tell us about yourself")),
	expectedField(
		"preferences",
		1,
		"f-newsletter",
		"newsletter",
		"checkbox",
		"Subscribe to Newsletter",
		described("Receive weekly updates"),
	),
]);

export const addressDefinition = expectedDefinition("nested-address", "root", [
	expectedField("root", 0, "f-name", "name", "text", "Full Name"),
	expectedField("root", 1, "f-email", "email", "email", "Email"),
	expectedSection("root", 2, "home-address", "Home Address"),
	expectedField("home-address", 0, "home-address-street", ["homeAddress", "street"], "text", "Street"),
	expectedField("home-address", 1, "home-address-city", ["homeAddress", "city"], "text", "City"),
	expectedField("home-address", 2, "home-address-state", ["homeAddress", "state"], "text", "State/Province"),
	expectedField("home-address", 3, "home-address-zip", ["homeAddress", "zipCode"], "text", "Zip/Postal Code"),
	expectedField("home-address", 4, "home-address-country", ["homeAddress", "country"], "select", "Country"),
	expectedSection("root", 3, "work-address", "Work Address"),
	expectedField("work-address", 0, "work-address-street", ["workAddress", "street"], "text", "Street"),
	expectedField("work-address", 1, "work-address-city", ["workAddress", "city"], "text", "City"),
	expectedField("work-address", 2, "work-address-state", ["workAddress", "state"], "text", "State/Province"),
	expectedField("work-address", 3, "work-address-zip", ["workAddress", "zipCode"], "text", "Zip/Postal Code"),
	expectedField("work-address", 4, "work-address-country", ["workAddress", "country"], "select", "Country"),
]);

export const settingsDefinition = expectedDefinition("settings-panel", "root", [
	expectedSection("root", 0, "notifications", "Notifications"),
	expectedField(
		"notifications",
		0,
		"f-notifications",
		"notifications",
		"checkbox",
		"Enable Notifications",
		described("Receive in-app notifications"),
	),
	expectedField(
		"notifications",
		1,
		"f-emailAlerts",
		"emailAlerts",
		"checkbox",
		"Email Alerts",
		described("Send email for important events"),
	),
	expectedField(
		"notifications",
		2,
		"f-pushNotifications",
		"pushNotifications",
		"checkbox",
		"Push Notifications",
		described("Mobile push notifications"),
	),
	expectedSection("root", 1, "appearance", "Appearance"),
	expectedField("appearance", 0, "f-darkMode", "darkMode", "checkbox", "Dark Mode", described("Use dark color theme")),
	expectedField(
		"appearance",
		1,
		"f-compactView",
		"compactView",
		"checkbox",
		"Compact View",
		described("Reduce spacing in lists"),
	),
	expectedField(
		"appearance",
		2,
		"f-fontSize",
		"fontSize",
		"number",
		"Font Size",
		described("Base font size in pixels"),
	),
	expectedSection("root", 2, "localization", "Localization"),
	expectedField("localization", 0, "f-language", "language", "select", "Language", { span: half }),
	expectedField("localization", 1, "f-timezone", "timezone", "select", "Time Zone", { span: half }),
	expectedSection("root", 3, "data", "Data & Privacy"),
	expectedField("data", 0, "f-autoSave", "autoSave", "checkbox", "Auto-Save", described("Automatically save changes")),
	expectedField(
		"data",
		1,
		"f-telemetry",
		"telemetry",
		"checkbox",
		"Usage Analytics",
		described("Help us improve by sharing anonymous usage data"),
	),
]);

export const productDefinition = expectedDefinition("product-entry", "root", [
	expectedSection("root", 0, "identity", "Product Identity"),
	expectedField(
		"identity",
		0,
		"f-name",
		"name",
		"text",
		"Product Name",
		describedHalf("Display name shown to customers"),
	),
	expectedField("identity", 1, "f-sku", "sku", "text", "SKU", describedHalf("Stock Keeping Unit identifier")),
	expectedField("identity", 2, "f-category", "category", "select", "Category", { span: half }),
	expectedSection("root", 1, "details", "Details"),
	expectedField(
		"details",
		0,
		"f-description",
		"description",
		"textarea",
		"Description",
		described("Detailed product description"),
	),
	expectedSection("root", 2, "pricing", "Pricing & Inventory"),
	expectedField("pricing", 0, "f-price", "price", "number", "Price (USD)", describedHalf("Retail price")),
	expectedField("pricing", 1, "f-weight", "weight", "number", "Weight (kg)", describedHalf("Shipping weight")),
	expectedField("pricing", 2, "f-quantity", "quantity", "number", "Stock Quantity", describedHalf("Units in stock")),
	expectedField(
		"pricing",
		3,
		"f-rating",
		"rating",
		"number",
		"Quality Rating",
		describedHalf("Internal quality score"),
	),
	expectedSection("root", 3, "status", "Status"),
	expectedField("status", 0, "f-isActive", "isActive", "checkbox", "Active", describedHalf("Available for purchase")),
	expectedField("status", 1, "f-isFeatured", "isFeatured", "checkbox", "Featured", describedHalf("Show on homepage")),
]);
