import { expectedDefinition, expectedField, expectedSection } from "./baseline-fidelity-helpers";

const half = { base: "full", md: 6 } as const;
const described = (description: string) => ({ description });
const describedHalf = (description: string) => ({ description, span: half });

export const vesselDefinition = expectedDefinition("custom-layout", "root", [
	expectedSection("root", 0, "identity", "Vessel Identity"),
	expectedField("identity", 0, "f-name", "vesselName", "text", "Vessel Name", { span: half }),
	expectedField(
		"identity",
		1,
		"f-imo",
		"imoNumber",
		"text",
		"IMO Number",
		describedHalf("International Maritime Organization number"),
	),
	expectedField("identity", 2, "f-callSign", "callSign", "text", "Call Sign", { span: half }),
	expectedField("identity", 3, "f-flag", "flag", "select", "Flag State", { span: half }),
	expectedSection("root", 1, "classification", "Classification"),
	expectedField("classification", 0, "f-type", "vesselType", "select", "Vessel Type", { span: half }),
	expectedField("classification", 1, "f-year", "yearBuilt", "demo16.range", "Year Built", { span: half }),
	expectedField(
		"classification",
		2,
		"f-active",
		"isActive",
		"checkbox",
		"Active",
		describedHalf("Currently in service"),
	),
	expectedSection("root", 2, "dimensions", "Dimensions & Capacity"),
	expectedField("dimensions", 0, "f-gt", "grossTonnage", "number", "Gross Tonnage", describedHalf("GT")),
	expectedField("dimensions", 1, "f-dwt", "deadweight", "number", "Deadweight", describedHalf("DWT in metric tons")),
	expectedField("dimensions", 2, "f-loa", "length", "number", "LOA (m)", describedHalf("Length Overall in meters")),
	expectedField("dimensions", 3, "f-beam", "beam", "number", "Beam (m)", describedHalf("Width at widest point")),
	expectedField("dimensions", 4, "f-draft", "draft", "number", "Max Draft (m)", describedHalf("Maximum draft")),
]);

export const responsiveDefinition = expectedDefinition("multi-section-responsive", "root", [
	expectedSection("root", 0, "personal", "Personal Details"),
	expectedField("personal", 0, "f-first", "firstName", "text", "First Name", { span: half }),
	expectedField("personal", 1, "f-last", "lastName", "text", "Last Name", { span: half }),
	expectedField("personal", 2, "f-dob", "dateOfBirth", "text", "Date of Birth", describedHalf("YYYY-MM-DD format")),
	expectedField("personal", 3, "f-gender", "gender", "radio", "Gender", { span: half }),
	expectedField("personal", 4, "f-nationality", "nationality", "text", "Nationality", { span: half }),
	expectedField("personal", 5, "f-passport", "passportNumber", "text", "Passport Number", { span: half }),
	expectedSection("root", 1, "emergency", "Emergency Contact"),
	expectedField("emergency", 0, "f-ecName", "emergencyContactName", "text", "Emergency Contact Name", { span: half }),
	expectedField("emergency", 1, "f-ecPhone", "emergencyContactPhone", "text", "Emergency Contact Phone", {
		span: half,
	}),
	expectedField("emergency", 2, "f-ecRel", "emergencyRelationship", "radio", "Relationship", { span: half }),
	expectedSection("root", 2, "health", "Health & Preferences"),
	expectedField(
		"health",
		0,
		"f-medical",
		"medicalConditions",
		"textarea",
		"Medical Conditions",
		described("List any relevant medical conditions"),
	),
	expectedField("health", 1, "f-dietary", "dietaryRequirements", "select", "Dietary Requirements"),
	expectedSection("root", 3, "agreement", "Agreement"),
	expectedField("agreement", 0, "f-terms", "agreesToTerms", "checkbox", "I agree to the terms and conditions"),
]);

export const minimalSourceDefinition = expectedDefinition("minimal-schema", "root", [
	expectedField("root", 0, "f-name", "name", "text", "name"),
	expectedField("root", 1, "f-email", "email", "email", "email"),
	expectedField("root", 2, "f-age", "age", "number", "age"),
	expectedField("root", 3, "f-role", "role", "select", "role"),
	expectedField("root", 4, "f-active", "active", "checkbox", "active"),
]);

export const explicitSourceDefinition = expectedDefinition("explicit-schema", "root", [
	expectedField(
		"root",
		0,
		"f-name",
		"name",
		"text",
		"Full Name",
		described("Your complete name as it appears on official documents"),
	),
	expectedField("root", 1, "f-email", "email", "email", "Email Address", described("Primary contact email")),
	expectedField("root", 2, "f-age", "age", "number", "Age", described("Your age in years")),
	expectedField("root", 3, "f-role", "role", "select", "User Role", described("Access level in the system")),
	expectedField(
		"root",
		4,
		"f-active",
		"active",
		"checkbox",
		"Account Active",
		described("Enable or disable this account"),
	),
]);

export const kitchenDefinition = expectedDefinition("kitchen-sink", "root", [
	expectedSection("root", 0, "text-inputs", "Text Inputs"),
	expectedField("text-inputs", 0, "f-text", "textField", "text", "Text Input", describedHalf("Standard text field")),
	expectedField(
		"text-inputs",
		1,
		"f-email",
		"emailField",
		"email",
		"Email Input",
		describedHalf("Email format validation"),
	),
	expectedField("text-inputs", 2, "f-url", "urlField", "url", "URL Input", describedHalf("URL format validation")),
	expectedField(
		"text-inputs",
		3,
		"f-required",
		"requiredField",
		"text",
		"Required Field",
		describedHalf("Shows 'Required' badge"),
	),
	expectedSection("root", 1, "textarea-inputs", "Textarea Variants"),
	expectedField(
		"textarea-inputs",
		0,
		"f-textarea",
		"textareaField",
		"textarea",
		"Textarea",
		described("Multi-line text via x-formbar widget hint"),
	),
	expectedField(
		"textarea-inputs",
		1,
		"f-longtext",
		"longTextField",
		"textarea",
		"Auto Textarea",
		described("Long text uses the supported textarea control"),
	),
	expectedSection("root", 2, "number-inputs", "Number Inputs"),
	expectedField(
		"number-inputs",
		0,
		"f-number",
		"numberField",
		"number",
		"Number Input",
		describedHalf("Free-form number"),
	),
	expectedField(
		"number-inputs",
		1,
		"f-integer",
		"integerField",
		"number",
		"Integer Input",
		describedHalf("Whole numbers only"),
	),
	expectedField(
		"number-inputs",
		2,
		"f-slider",
		"sliderField",
		"number",
		"Value from 0 to 100",
		describedHalf("Constrained integer rendered as a native number"),
	),
	expectedField(
		"number-inputs",
		3,
		"f-with-default",
		"withDefault",
		"text",
		"With Default Value",
		describedHalf("Pre-populated from initial data"),
	),
	expectedSection("root", 3, "selection-inputs", "Selection Controls"),
	expectedField(
		"selection-inputs",
		0,
		"f-radio",
		"selectSmall",
		"radio",
		"RadioGroup (≤5 options)",
		described("Stored values use the original option order"),
	),
	expectedField(
		"selection-inputs",
		1,
		"f-select",
		"selectLarge",
		"select",
		"Select (>5 options)",
		described("Larger enums render as select dropdown"),
	),
	expectedSection("root", 4, "boolean-inputs", "Boolean Controls"),
	expectedField(
		"boolean-inputs",
		0,
		"f-switch",
		"switchField",
		"checkbox",
		"Switch Toggle",
		described("Boolean field uses a native checkbox"),
	),
]);
